### PR TITLE
Add Icon and Fanart for Repository

### PR DESCRIPTION
**Pull request by 32Dexter**
Hi, you can add:
/resources/icon.png
And
/resources/fanart.jpg
in /matrix/zips/plugin.video.discoveryplus/ ?
https://github.com/Dis90/dis90.github.io/tree/matrix/zips/plugin.video.discoveryplus/
So your repository is much nicer
Thanks a lot

### CODE REVIEW

**Comment by Dis90** [comment]
Images are now in wrong place. Correct place is https://github.com/Dis90/dis90.github.io/tree/master/repository.dis90
Can you also made PR to matrix branch?

**Comment by 32Dexter** [comment]
The Icon and Fanart of the Repository are correct.
But if you enter in you Repository from Kodi and enter in Add-on Video, you see your Add-on Discovery Plus but there is not the Icon and Fanart:
discovery_repo
If you see the image, you can see Kodi not see the icon and fanart.
If you merge this modify, i correct this problem.
Thanks

**Comment by 32Dexter** [comment]
> Can you also made PR to matrix branch

This change is for the Matrix branch, sorry I forgot

**Comment by Dis90** [comment]
> If you merge this modify, i correct this problem.

Are you sure that this fixes anything? Do you have example how other repositories have made?

> This change is for the Matrix branch, sorry I forgot

You have made this change to master branch and that is for Kodi Leia. You need to made it to matrix branch.

**Comment by 32Dexter** [comment]
> Are you sure that this fixes anything? Do you have example how other repositories have made?

Yes, I'm sure it solves the problem (but it's only aesthetic).
Basically only the folders are created and the images of the add-on are loaded. If you check the Kodi Log when you enter your repository it appears that Kodi tries to open icon.png and fanart.jpg but without success because they do not exist.

> You have made this change to master branch and that is for Kodi Leia. You need to made it to matrix branch.

You're right, I realized after doing the Pull. Excuse me!
Do I have to redo the Pull or can you insert the folders and images yourself?
Thanks a lot

**Pull request merged**
